type categories  {
    id: ID!
    name: String!
}
type prices{
  id: Int!
  product_id: String!
  amount: Float!
  currency: String!
}
type currencies {
  id: ID!
  label: String!
  symbol: String!
}

type products {
  id: ID!
  name: String!
  in_stock: Boolean!
  description: String!
  attributes: String # Allow null for attributes
  category_id: ID!
  brand: String!
  price: Float
  image: String!
 attributess: [attributes] 
 category:[categories]
}


type attributes {
  id:ID!
  name:String!
  type:String!
}


type productimages {
    id: ID!
    product_id: ID!
    image_url: String!
}
type products_attributes {
  id:ID!
  attribute_id:ID!
  item_displayValue:String!
  item_id:ID!
  product_id:ID!
}
scalar JSON

type Mutation {
  createOrder(
    product_id: ID!,
    product_name: String!,
    description: String!,
    total_amount: Float!,
   attributes: String!,
    quantity: Int!
  ): orders
}


type orders {
  id: ID!
  product_id: ID!
  product_name: String!
  description: String!
  total_amount: Float!
  attributes: JSON!
  quantity: Int!
}

type Query {
    categories: [categories] @all
    orders:[orders] @all
    products: [products] @all
    currencies: [currencies] @all
    product(id: ID!): products
    productimages: [productimages] @all
    productsByCategory(category_id: ID!): [products!]!
    attributes: [attributes] @all
    products_attributes: [products_attributes] @all
    prices: [prices] @all

}








